### ISSUE TITLE
Configure scripts for test, build, and deploy

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-2.0-coping-strategies#1]
We should add the necessary scripts and other configuration so that we can run automated tests and build & deploy the same way as our other Scratch 3 repositories.

**Comment by fsih** [comment]
<strike>We should really consider looking at this before launch, especially now that it runs code when loaded. Other repos still depend directly on the github repo for this repository, which means changes to it could break production.</strike>

<strike>Putting in June so we look at it</strike>

Oh wait, I was talking about scratch-render-fonts. This repo is already set up to deploy

**Comment by fsih** [comment]
Don't mind me
